name: CI (docs)

on:
    # We do not need a push event to master here, since the doc deploy will verify the code anyway.

    pull_request:
        branches:
            - main
        paths:
            - "src/**"

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 12.x

            - name: Install Docusaurus
              run: npm install
              working-directory: ./docs

            - name: Build
              run: npm run build
              working-directory: ./docs
