name: CI (lib)

on:
    push:
        branches:
            - main
        paths:
            - "src/**"

    pull_request:
        branches:
            - main
        paths:
            - "src/**"

jobs:
    ci:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependancies
              run: npm install

            - name: Build
              run: npm run build

            - name: Test
              run: npm run test

            - name: Lint
              run: npm run lint
