name: Node.js CI

on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node.js 14.x
              uses: actions/setup-node@v2
              with:
                  node-version: 14.x

            - name: Build, Test, Lint
              run: |
                  npm install
                  npm run build
                  npm run test
                  npm run lint

            - name: Build Documentation
              run: |
                  cd docs
                  npm install
                  npm run build
